version: '3.7'

x-env-defaults: &env
  YARN_CACHE_FOLDER: /.yarn-cache
  NODE_ENV: development

x-node-defaults: &node
  tty: true
  init: true
  image: node:10.15
  entrypoint: ["node"]
  working_dir: /leadership-update
  volumes:
    - .:/leadership-update:cached
    - ./node_modules:/leadership-update/node_modules:delegated
    - yarn-cache:/.yarn-cache
  environment:
    <<: *env

services:
  commands:
    <<: *node
    working_dir: /leadership-update
    entrypoint: ["tail"]
    command: ["-f", "/dev/null"]

  config-server:
    <<: *node
    working_dir: /leadership-update/services/config-server
    entrypoint: ["./node_modules/.bin/gulp"]
    environment:
      <<: *env
      TENANT_KEY: ${TENANT_KEY-as3_baseplatform}
      GRAPHQL_URI: ${GRAPHQL_URI-https://caprica.graphql.base-cms-staging.io}
    ports:
      - "13001:80"

  portal:
    <<: *node
    image: danlynn/ember-cli:3.13.0
    working_dir: /leadership-update/services/portal
    entrypoint: ["ember"]
    command: ["serve", "--port", "13002", "--proxy", "http://config-server"]
    tmpfs:
      - /leadership-update/services/portal/tmp
    ports:
      - "13002:13002"
    depends_on:
      - config-server

volumes:
  yarn-cache: {}
